# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-extractor-backend
    ports:
      - "8000:8000"
    environment:
      # This will use the GEMINI_API_KEY passed at runtime
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - pdf-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdf-extractor-frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - pdf-network
    restart: unless-stopped

networks:
  pdf-network:
    driver: bridge
